Netlogix:
  Supervisor:

    # List of class names implementing \Netlogix\Supervisor\Provider
    providers:
      ConfigurationBased: \Netlogix\Supervisor\ConfigurationBased\Provider

    # List of program groups
    groups:

      default:
        # Maps to a Supervisor group name.
        # Gets cleaned up to not contain invalid characters as of supervisor settings
        #
        # In general, `supervisorctl restart default:` calls are limited to only one
        # specific group.
        # If multiple flow instances share a common supervisor daemon, the unique group name
        # per flow instances allows restart calls on deployment that don't affect other flow
        # instances.
        # This can be changed to e.g. `name: "%FLOW_PATH_ROOT%"`
        #
        # Defaults to the array key if not present.
        name: "default"

        # Defaults to 999
        priority: 100

    # List of supervisor programs
    # See Configuration.yaml.example for examples and description
    programs: []
